version: "3.7"
services:
  mongo_service:
    build: .
    restart: always
    ports:
      - "3010:3011"
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"